### ISSUE TITLE
Needs updates for beta3

### ISSUE THREAD

**Issue by Daniel15** [Shazwazza/Smidge#1]
ASP.NET 5 beta3 changed `IContextAccessor<HttpContext>` to `IHttpContextAccessor` :+1:

**Comment by Shazwazza** [comment]
Yup :) 

I had done an update before beta3 was released but unfortunately at that time the build had issues so I decided to just wait until things were a little more stable. There's a few other things that need to be updated as well since IContextAccessor doesn't exist at all anymore IIRC and it's currently being used to get access to other context's like ActionContext, etc...

**Comment by Shazwazza** [comment]
new release out: https://github.com/Shazwazza/Smidge/releases/tag/1.0.0-beta1
