### ISSUE TITLE
Multiple named anonymous view based declarations?

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/Smidge#115]
Wondering if multiple named anonymous view based declarations might be possible?

In addition to a **Common Bundle plus Page Specific Bundle** approach

allowing developers to create partial views that have css/js dependencies these would then be added at will to a view so that page specific bundle is dynamic @ runtime.
### partial one
```
@{ Smidge.RequiresJs("~/Js/test1.js", "~/Js/test2.js", "//cdn/jquery.js"); }
@{ Smidge.RequiresCss("~/Js/test1.css", "~/Js/test2.css", "//cdn/a.css"); }
```
### partial two
```
@{ Smidge.RequiresJs("~/Js/test3.js", "~/Js/test2.js"); }
@{ Smidge.RequiresCss("~/Js/test3.css", "~/Js/test2.css", "//cdn/a.css"); }
```

As I understand it at present I can use the anonymous view based declaration and de duped css/js would end up at the relevant
### View
```
@await Smidge.CssHereAsync()
@await Smidge.JsHereAsync()
```

However, from those two partials.. I don't have any control over the order that they render in the combined output?
Also if I had js/css that needs to be in the header (above fold render) as opposed to the footer (avoid render blocking)  I can't do that?

If then I also wanted a common site wide bundle that included external assets.. I'd need to use the anonymous view based approach again. which can only render into the one anonymous view based declaration, so couldn't actually do the **Common Bundle plus Page Specific Bundle** approach?

Can we dynamically add additional files into an existing bundle with priority? (all be it sacrificing the external asset support)
Or maybe some if not all of the above is possible with .net core which is very new to me?

You might have guessed that I'm coming from clientDependency framework here and the ForcedProvider facility :-) that allowed the above.

**Comment by Shazwazza** [comment]
Please do not use bundles in partial views. As you've noted there's no way to control the order. It simply cannot work. This works in CDF by a huge amount of hacking which is  not supported in netcore and I really don't want to go down that road. Doing any logic within partial views, like dynamically adding to a bundle will be problematic - there is no control over when that code will execute.

It's best to just create bundles. You can create bundles dynamically and then include those in views that need them.

**Comment by mistyn8** [comment]
Thanks for the response. I don't think I was suggesting using bundles in partials, the bundle would be in the view.. but the partial would like to say I need this in the bundle.. for blocklist / doctypegrid say in Umbraco.. 
Am I missing something where a view can interrogate what partials are in use at runtime (hence the css/js for those partials) and dynamically create a bundle to include in the view?

**Comment by Shazwazza** [comment]
Views are compiled and executed as they are registered. It's an inside out process. The outer view has no ideal what inner views are being rendered. Views don't have any context to know what is being rendered or what has already been rendered. This was possible back in webforms because the entire control hierarchy needed to be known to render one page which was horrible for performance. 

Views are just bits of c# at the end of the day. The code executes when they are asked to render which is what the Razor engine does. 

This syntax of dynamically declaring non-named bundles:

```
@{ Smidge.RequiresJs("~/Js/test3.js", "~/Js/test2.js"); }
@{ Smidge.RequiresCss("~/Js/test3.css", "~/Js/test2.css", "//cdn/a.css"); }
```

is pretty old school and as you've noted cannot work with partial views because you have no way to know if your partial has executed (and therefor required these files) before the call to render the bundle is make. If this could even work, this also means you can end up with tons of different bundle hashes based on the pages rendering because the views included in the page might be different. This can be problematic on it's own and you'll reduce performance instead of gaining performance.

You're better off, pre-defining your bundles in c# with names. I think trying to mix and match dynamic assets based on what is included in your block editor is going to cause more problems than it's worth. Having one named/pre-defined bundle for all things that might be included in your block editor is the way to go. If you're hell bent on having different/smaller bundles based on what is rendering in the block editor, you will have to pre-emptively inspect the data in the block editor and determine what assets are needed and then render it. But I would advise on not using the dynamic/non-named RequireJs/RequireCss approach.

**Comment by mistyn8** [comment]
Thank you very much for engaging ;-)

use case that I'm thinking of is say a partial for a calendar as the only thing that requires jquery + jqueryUI.. or some other heavy css/js dependency... now as that can be dynamically included via a partial in the cms it may never be used.. but in order to go with bundling I'd have to include that for the possibility it might get used by someone at some point?

maybe very judicious use of dynamic/non-named RequireJs/RequireCss would mitigate the inclusion of large dependencies.

again thanks or the advice. ;-)

**Comment by mistyn8** [comment]
ps what's your take on approaches like https://www.devready.co.uk/post/scripts-section-in-asp-net-core-partial-view or https://codeshare.co.uk/blog/how-to-include-scripts-from-partial-views-in-mvc-and-umbraco/

could the enumeration then generate a named bundle and include dynamically in the view context.. to gain minification/combination?

**Comment by Shazwazza** [comment]
Nothing stopping you from trying the HttpContext tricks, just beware that depending on how your partial views are rendered and where you scripts are rendered and if you use view components, etc... things might not always work as expected. Ultimately, it just comes down to how you want to work, how you want to render your views and where your scripts are output.

If you are building up dynamic bundles, then you cannot use a named bundles because it will potentially contain different scripts for each page. You would need to use the dynamic bundling like `@{ Smidge.RequiresJs("~/Js/test3.js", "~/Js/test2.js"); }` to do that.
