### ISSUE TITLE
Builder.ForDebug().ForProduction()

### ISSUE THREAD

**Issue by mistyn8** [Shazwazza/Smidge#137]
More a question as to how this works..
Development is the only Environment where  (Appsettings.Development.json)
```
  "Umbraco": {
    "CMS": {           
      "Hosting": {
        "Debug": true
      },
```
If I have 
```
bundles.CreateJs("sitewide-js", //bundle-name
		"~/js/debounce-throttle.js"
		)
	.WithEnvironmentOptions(BundleEnvironmentOptions.Create()
	.ForDebug(builder => builder
		.EnableCompositeProcessing()
		// should drop the cache each apprecycle
		.SetCacheBusterType<AppDomainLifetimeCacheBuster>()                        
	)
	.ForProduction(
		builder => builder
		.EnableCompositeProcessing()
		.EnableFileWatcher()
		// should drop the cache each time the version changes in appsettings
		.SetCacheBusterType<ConfigCacheBuster>()
		.CacheControlOptions(enableEtag: false, cacheControlMaxAge: 30)
		)   
	.Build());
```
When I spin up that site locally in visual studio debugging in kestrel
<link rel="stylesheet" href="sitewide-css" /> returns <link href="/sb/sitewide-css.css.v22" rel="stylesheet" /> the ForProduction settings even though this is a debug set environment.

I had seen the render options for is environment tag helper add a debug=true into the cache helper but assumed that this was an override for the setting set ForDebug... rather than needing to pass back that I'm debug...

So is it the case that having the above builder, is more to do with waiting for a request to come in from the render of either debug=true or not.. and it then creates the required file? Rather than my assumption that the bundle is generated at startup dependant on the environment settings matching ForDebug vs ForProduction?

Maybe my confusion is that ForProduction would seem to imply a mapping to APSNET_ENVIRONMENTNAME = "Production" so when I have APSNET_ENVIRONMENTNAME =Development this config should not be in play.
Whereas actually, ForProduction is not that at all.. and just when debug=true isn't asked for from the view?

Is ForDevelopment, ForStaging, ForProduction a possibility? And Startup.cs being the only place we need to configure these?
Not that I know much about how builders work ;-)

**Comment by Shazwazza** [comment]
Smidge doesn't adhere to any debug environment variables. It is up to you how you want to render - either in debug mode or not using the isDebug flag (which you could set with whatever variable you want). Smidge also knows nothing of Umbraco so any Umbraco settings do not apply to Smidge (standalone). However, Umbraco implements Smidge independently of how Smidge would work on the front-end and Umbraco might use it's own Debug configuration flag to determine how to render it's own bundles, but this debug flag does not impact your own bundles.

Each bundle you create can be rendered and configured in both Debug mode or Production mode. This is NOT the same as environment variables. There are only 2 configurations per bundle, it doesn't make sense to have more - a Staging bundle should just be rendered as Production since you are not debugging the bundle. 

See rendering docs for more info: https://github.com/Shazwazza/Smidge#rendering , https://github.com/Shazwazza/Smidge/wiki/Rendering

**Comment by mistyn8** [comment]
@Shazwazza Thanks for the quick reply and clarification... All seems down to confusion on my part stemming from netcore terminology vs Smidge terminology ;-)

As I understand it..
netcore has a concept of the DEBUG constant.. (which can be set/unset for any build config)
and `#If DEBUG` then used.

Microsoft talk of `Debug` vs `Release` , and environments of `Development`, `Staging`, `Production` (and provide `IWebHostEnvironment` `isDevelopment`, `isStaging`, `isProduction` 

But that's not to say we can't add a named debug or release environment and use `isEnvironment("xxx")`

So yep all confusion relating to `forProduction` inferring the MS environment, and not maybe aligned to `forRelease`.

And smidge Debug is simply Smidge debug mode, and smidge ForProduction is just NOT Smidge Debug, 
and that's completely your prerogative to name as you wish for your needs. :-)

Hopefully, user feedback like this is useful?
But thank you all sorted in my mind, at least at the moment. :-) 

Oh just on the ForStaging... I had thought a usecase might be 
DEBUG
`.CacheControlOptions(enbleEtag: false, cacheControlMaxAge: 0)`
STAGING
`.CacheControlOptions(enableEtag: false, cacheControlMaxAge: 1)`
PRODUCTION
`.CacheControlOptions(enableEtag: false, cacheControlMaxAge: 30)`

**Comment by Shazwazza** [comment]
Yes but you can still 100% control that behavior based on any variables you want, so if you are in staging you can set the cache control options to be what you wish.
