### ISSUE TITLE
Guidance around bundling external assets

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#20]
This is not a Smidge issue exactly, but is loosely related. I was wondering what best practice might be for dealing with external resources such as jquery, font-awesome etc. Would it be best to bundle these all together into a single local file?

MVC 6 allows you to include references to external files (from a CDN etc) with a fallback to a local file when that file isn't available like this:

```

<environment names="Test,Staging,Production">
        @*<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />*@
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css"
              asp-fallback-href="~/lib/font-awesome/css/font-awesome.min.css"
              asp-fallback-test-class="fa" asp-fallback-test-property="display" asp-fallback-test-value="inline-block"/>        
    </environment>

```

So at the moment i'm assuming its best to stick to this mechanism and do not bundle external resources, just let them load individually..

**Comment by Shazwazza** [comment]
Smidge will actually handle external resources as well, however IIRC it doesn't do that for named bundles, only for anonymous view based declarations. The way it does that is it detects the inputs and outputs them staggered. For example if you did:

```
@Html
   .RequiresJs("~/Js/script1.js")
   .RequiresJs("~/Js/script2.js")
   .RequiresJs("http://blah.com/js/somescript.js")
   .RequiresJs("~/Js/script3.js")
   .RequiresJs("~/Js/script4.js");
```

you'd actually get 3x <script> tags output, the first would be the bundle of script1+script2, then it would output a script tag for the external resource, then the third would be the bundle of script3+script4.

But for a named bundle it throws an exception if you try to add an external resource to it (https://github.com/Shazwazza/Smidge/blob/6db4fbeb3e41b3a38b31a351550226612bd3985b/src/Smidge/SmidgeBundleContext.cs#L24) . That's because a named bundle only every has one URL

So if you are mixing named bundles with external assets, you'll have to render them out in the order you need, or you can register your external assets with view based declarations. I haven't really added any smart support for that like CDN falling back to local files, etc... might be able to add some support for those things though in the future.

**Comment by dazinator** [comment]
ah ok.. so if you did:

```

@Html
   .RequiresJs("~/Js/script1.js")
   .RequiresJs("~/Js/script2.js")
   .RequiresJs("~/Js/script3.js")
   .RequiresJs("~/Js/script4.js");
   .RequiresJs("http://blah.com/js/somescript.js") 

```

Then you'd get 2x ?

**Comment by Shazwazza** [comment]
Yup

**Comment by dazinator** [comment]
Ok, i don't actually use the "on demand" style above, i use named bundles, so i'm guessing smidge wont support external resources for named bundles. I'm gonna close this as I think for producing named bundles, using local resources is the way to go anyway.
