### ISSUE TITLE
Default pre-processor pipeline - don't enable JsMin for .min.js files convention

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#21]
Just wondered if it would be a good enhancement for `Smidge` to not use the `JsMin` `PreProcessor` by default for `.js` files ending in `.min.js`. ? Not sure how that could work right now but I am guessing it owuld be something like after the `PreProcessorPipelineFactory` is invoked to get the default pipeline for `.js` files, inspect that pipeline, and if there are files in the bundle ending in `.min.js` and those files don't have a custom pipeline set, then give those files a custom pipeline based on the default, minus `JsMin` ?

**Comment by Shazwazza** [comment]
Yup that's probably a great convention!

**Comment by Shazwazza** [comment]
Cool this is all implemented now. You can register any custom `IFileProcessingConvention` in IoC and it will execute for all registered IWebFiles which you can then adjust the pre-process collection for that file accordingly. There's one registered that will remove the jsmin or cssmin for any file ending in min.css or min.js

I suppose this should be changed a bit so that it's not done via IoC since you won't be able to remove it from IoC if you don't like that convention so I think i'll need to change it to options or something.
