### ISSUE TITLE
cache busting effectively doesn't work

### ISSUE THREAD

**Issue by Superhands89** [Shazwazza/Smidge#212]
Reading this first may help
https://github.com/umbraco/Umbraco-CMS/issues/15165

but is it possible to iterate the .v1 that appears at the end of my bundled JavaScript in an automated way?
Without this feature I can't see how Smidge is usable out of the box.

**Comment by Shazwazza** [comment]
Lets keep the discussion open in the Umbraco tracker because this is an Umbraco integration issue. If you use Smidge without Umbraco it will work as expected. Umbraco attempts to use Smidge for its backoffice usages without trying to interrupt how Smidge should work on the front-end. I can't recall exactly how this is done but as you can see in the other discussion, there are Umbraco specific cache buster settings, etc... - these don't exist in this repo, so it is an implementation in Umbraco that changes the expected behavior. This will probably also depend on if you are using Smidge in the back office or the front-end.

If it is for the front-end, have you tried just using Smidge with Smidge settings (don't use any Umbraco settings) i.e. https://github.com/Shazwazza/Smidge?tab=readme-ov-file#pre-defined-bundles
