### ISSUE TITLE
Core RC2 Support?

### ISSUE THREAD

**Issue by cindro** [Shazwazza/Smidge#34]
Any plans of upgrading the current package and its dependencies to support RC2?

Can't get your updated sample app to work for me.

**Comment by Chimeran** [comment]
Do you refer to ASP.NET Core 1.0 RC2?

I have started working on this. You can get it here:

[Link](https://github.com/Chimeran/Smidge)

**Comment by Shazwazza** [comment]
I've pushed two commits already that have already updated to RC2, the only remaining thing is to convert the Tests project.

**Comment by Shazwazza** [comment]
commits: e6d1aaf1807a21988259ea308d217f95b62e4b3d, 21bc5135352d221bb603e65234b2be6a0ac79047

**Comment by Shazwazza** [comment]
I've commented on the requirement of IUrlHelperFactory since it's a shame to add so much weight to just be able to use the `Content` method: https://github.com/aspnet/Mvc/issues/3936#issuecomment-220634847

In this core I've created simpler object to use: `Smidge.Models.RequestParts` which doesn't require registering IUrlHelperFactory in DI, but of course means that RequestParts is, but this is taken care of by  `AddSmidge`

**Comment by Shazwazza** [comment]
This is all complete in this rev: 8736caf01b76cdaabba22b6497992a54348de486

All tests pass, the test web proj is working. Now I just need to update the build script to work.

**Comment by cindro** [comment]
Thank you so much for your hard work, I look forward to the build.

**Comment by Shazwazza** [comment]
Finally got this live: https://www.nuget.org/packages/Smidge/1.0.0-rc7
I sort of mucked up a couple of uploads so it's jumped from rc4 -> rc7 :)

**Comment by cindro** [comment]
I can't get the latest rc7 to work on ASP.Net Core RC2, weird.

Please check if you can get it to run on ASP.Net Core RC2? Thank you.
