### ISSUE TITLE
NUglify

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#43]
Have you seen https://github.com/xoofx/NUglify ? 
It has some interesting stuff in there. I only stumbled accross it because mads is using it as a dependency in the bundler that is included by default in the latest aspnet core website project templates: https://github.com/madskristensen/BundlerMinifier

I think I'm going to give it a whirl in `NetPack` to see how well the source maps work.

**Comment by Shazwazza** [comment]
Ah cool, was wondering when someone would port ajaxmin. It builds an whole AST to do its minifying which is generally going to be much slower than jsmin, but will be able to make it smaller. Same goes for uglify in JS. Part of the reason smidge persists the already bundled files to disk is to avoid the performance penalty on each restart. Would be interesting to do some benchmarks

**Comment by Shazwazza** [comment]
This is already in there now, i'll need to make a separate nuget package for this as I don't want to ship with it in by default, similarly the JavaScript services Uglify is all in there too. I've put benchmarks together here though so you can see why JsMin is preferred as a runtime minifier: https://github.com/Shazwazza/Smidge/wiki/Custom-pre-processing#minification-benchmarks

**Comment by Shazwazza** [comment]
Actually, I'll reopen to enable passing custom options to this pre-processor without having to override it.

**Comment by Shazwazza** [comment]
@dazinator I've updated lots of code now, the Nuglify part is now working quite well and you can pass in custom uglify parameters. 

What I've been working on today though is getting source maps working with Nuglify which isn't all that straight forward but it's now working and working with inline source maps. You can see my latest commit here https://github.com/Shazwazza/Smidge/commit/89a78625a9f382508dc2c980f76c43a38a856778 which has some notes and notes in the code.

The problem now is that the inlined source maps will be appended just after the minified file, but that means when the files are bundled together there will be multiple inline source maps which isn't supported. So when it renders in chrome, chrome only detects the sourcemap declared at the very bottom. I've added notes here https://github.com/Shazwazza/Smidge/commit/89a78625a9f382508dc2c980f76c43a38a856778#diff-e0341dfe46fc118418bb20019d3eb0b9R26 about this since I think it will require a refactor of how file processors can interact with the bundling/combination logic, then need to figure out how to combine sourcemaps - I've added some link references and funny enough one of the articles I found had you in it!

**Comment by dazinator** [comment]
Hmm - I ended up writing a dotnet class that combines multiple sourcemaps and outputs a single "index source map.". Basically when i combine seperate files into one, i detect and parse the source maps from the seperate files, combine them into an index source map, then outout the index source map at the end of the new file. You are welcome to look at the source code for that if you want. I did have issues with index source maps not working in edge though and i never resolved that.

**Comment by dazinator** [comment]
Tests for that process if curious are here: https://github.com/dazinator/NetPack/blob/develop/src/NetPack.JsCombine.Tests/CombinePipeTests.cs

I'll checkout the latest smidge code and give it a whirl :-)

**Comment by Shazwazza** [comment]
The latest commits now have source maps working with Nuglify both default (external file source maps) and inline (if  you choose to configure it that way)!

The `V3SourceMap` class in Nuglify (well taken from AjaxMin) is odd but it actually lets you incrementally apply a single instance to multiple files without having to tell it up-front what all of  the files are and it's smart enough to iteratively update its `sources` list. 

I've made the default options to use normal (non-inline) source maps, since inline ones just make files huge and it all works very well! If you pull the latest changes and F5, the test website will start and one of the bundles is configured to use Nuglify: `libs-js` which includes jquery + knockout. This will have a source map applied to it and you can inspect it in Chrome that it's all working.

Smidge 2.0 is *so* close now.
