### ISSUE TITLE
Named bundles should execute the pipeline (if not already done) when the bundle URL is visited

### ISSUE THREAD

**Issue by josh-sachs** [Shazwazza/Smidge#45]
The following setup is not working when debug is false. 

```
"Smidge": "1.0.0"

bundles.Create("jquery", WebFileType.Js, "~/lib/jquery/3.1.0/jquery.js");
@await Smidge.JsHereAsync("jquery", false)
```

The Javacript file is non-minified, unmodified distribution of jquery 3.1.0 hosted localy in wwwroot/lib/...

In debug mode, the file is found and included as scrip tag.  When debug is false, it looks like Smidge is creating assets correctly in the disk cache, but the content rendered when the bundle is requested by the browser is just a semi-colon ';'.

**Comment by kudoz83** [comment]
I'm not sure what's going on here actually.   

In the previous post I left out the fact that was doing a Directory.Delete of the file cache prior to adding Smidge to the services collection (I have another ticket about opting out of disk-cache).   I didn't think it was relevant because I would expect deleting the cache to produce the same results as re-versioning. 

If i delete the disk cache, and restart the application, clear browser cache - failure to increment the version will result in unexpected behavior from Smidge... I would expect that if a version folder doesn't exist in the Smidge dataFolder, Smidge would treat requests for that resource as if it were the first time it has seen that version. 

Here is an attempt at repro steps: 

```
1. set version = "1000000000"
2. visit index.cshtml that has a call to Smidge.JsHereAsync("bundle", false)
3. navigate to /sb/app.js.v1000000000
```
This looks right so far...

```
4. stop application.
5. delete dataFolder
6. clear browser cache
7. navigate to navigate to /sb/app.js.v1000000000
8. observe blank content returned. 
9. observe dataFolder has a gzip created, but none of the js files that would normally be zipped up were created. 
10. navigate to the index page that has a call to Smidge.JsHereAsync("bundle", false)
11. notice the js files now get added to the cache (but i dont think gzip file is updated)
```

This breaks down... obviously there is something happening out of order in the above steps (visit to the bundle resource before visit to the View).   If you swap those two steps, it still returns empty content.

```
12. stop application
13. delete dataFolder
14. clear browser cache
15. increment version
```

Everything works as expected.... a fix for the time being is to set the config[version] = DateTime.UtcNow.Ticks.ToString() prior to passing the config into Smidge.  I still do the Directoy.Delete to keep the App_Data folder clean. 

Sorry if this isn't clear enough to follow - let me know and I'll try to clean it up.

**Comment by Shazwazza** [comment]
Hi,

This is because of how Smidge works - currently the view rendering (i.e. the calling of `JsHereAsync`) is what creates the pipelined files. So if you just hit the URL and these files don't exists there is no way for it to process these files. 

This could be updated to perform the pipelining for named bundles when the request is made, but it would not be possible to do that for un-named bundles (i.e. view based declarations). But yes, i think it should check if the pipelining hasn't been done based on a named bundle URL and if not it will perform the processing.
