### ISSUE TITLE
Working with a custom RequestPath with StaticFileOptions and SourceMaps

### ISSUE THREAD

**Issue by kostyrin** [Shazwazza/Smidge#74]
So, I have a trouble.
When I use in Startup
in Startup.ConfigureServices(IServiceCollection services) I have a code:
`services.AddSmidge(Configuration.GetSection("smidge"), new PhysicalFileProvider(modulesDiscoveryPath));
            services.AddSmidgeJavaScriptServices();
            services.AddSmidgeNuglify();`
and in Configure(IApplicationBuilder app, IHostingEnvironment env) I have a code:
`new StaticFileOptions()
 {
                    FileProvider = new PhysicalFileProvider("C:\Module1\Module1.Web"),
                    RequestPath = new PathString($"/Modules/$({ module.ModuleName })")
                }`
`app.UseSmidge(bundles => { app.UseModulesContent(bundles); });
            app.UseSmidgeNuglify();`
and load bundles like that
`bundles.Create("modules-scripts", bundles.PipelineFactory.Create<NuglifyJs>(), jsFiles.ToArray())
                   .WithEnvironmentOptions(options);`
There is a code in _Layout:
`<script src="modules-scripts" type="text/javascript"></script>`
Then I get in the result sourceMap-folder:
![image](https://user-images.githubusercontent.com/8361000/37038451-80180658-215d-11e8-919f-b5a67a94c7f5.png)
but I have a wrong path like /Module1/Module1.Web/Scripts/module1.js
instead of a true path: /Modules/$(Module1)/Scripts/module1.js
What should I do for getting a true path?

**Comment by Shazwazza** [comment]
Would you be able to re-post your whole startup code in correct code blocks? it's just difficult to see exactly what you are doing.

Code blocks should be like (between 3x backticks), or you can indent the whole thing, see https://guides.github.com/features/mastering-markdown/#examples:

    ```
    function fancyAlert(arg) {
      if(arg) {
        $.facebox({div:'#foo'})
      }
    }
    ```

**Comment by kostyrin** [comment]
I can see the Startup in this link: https://github.com/VirtoCommerce/vc-platform-core/blob/feature/notifications/VirtoCommerce.Platform.Web/Startup.cs

**Comment by Shazwazza** [comment]
I think its the implementation of how Smidge and the Nuglify provider are currently working. They don't really have any knowledge of any custom StaticFileOptions parameters, especially since those are used for different middleware entirely. 

I think to make it work the way you want these StaticFileOptions would need to be passed into Smidge one way or another. 

If you wanted to debug into this, you can clone this repo, build the sln and drop in the debug DLLs into your project and add a breakpoint. I think the map urls are done here https://github.com/Shazwazza/Smidge/blob/master/src/Smidge.Nuglify/SourceMapDeclaration.cs#L22 

Smidge just knows about the physical file system and the application root so it just does maps paths based on that, I "think" to support this, it would need to support custom static file request options. I'd really need to debug into it to fully understand but unfortunately i don't have a whole lot of time at the moment. 

Any feedback/help is appreciated

**Comment by kostyrin** [comment]
Ok. Thank's
If I make a pull request, will You have time for to merge the request?

**Comment by Shazwazza** [comment]
Yup sure! Happy to assist where i can, just no time at the moment to setup a repro of the issue, a PR would be amazing and we can go from there.

**Comment by kostyrin** [comment]
please, check PR https://github.com/Shazwazza/Smidge/pull/76

**Comment by kostyrin** [comment]
Can you make a release?

**Comment by Shazwazza** [comment]
I haven't had a chance to look yet, i can do that tomorrow for you

**Comment by Shazwazza** [comment]
I realize this is incredibly old and I'm sorry for that. There's not been any other requests for this feature however I've finally looked into this to see what can be done and realized that this can be worked around 'now' without modifying the core in theory.

Since this issue is purely about working with Nuglify and Source maps, it would be possible to:

1. Adjust the pre-process pipeline and insert your own custom pipeline just before and just after the NuglifyJs one.
1. The custom pre-processor before, would set the `fileProcessContext.WebFile.FilePath` to the `RequestPath` that you need 
1. The custom pre-processor after, would restore this value to what it was

Then when NuglifyJs runs it will use the custom RequestPath. You can store the original path in the `fileProcessContext.BundleContext.Items` in the pre-processor running before NuglifyJs which will be retrieved in the custom pre-processor that runs after NuglifyJs to restore the value.

Alternatively, I can add functionality where the NuglifyJs processor will first check in the `fileProcessContext.BundleContext.Items` for a special key indicating the RequestPath which could be set with a custom processor like in 2) mentioned above and then there would be no reason to restore.

**Comment by Shazwazza** [comment]
I have pushed a change and will make a release. The `NuglifyCss` and `NuglifyJs` both now have a virtual method that can be overridden: `protected virtual UglifyResult NuglifyProcess(FileProcessContext fileProcessContext, CodeSettings codeSettings)`. This means you can create your own sub class of `NuglifyJs` and override `NuglifyProcess` to change the file path (i.e. to a custom request path). Then you can use your custom sub-class as the pre-processor in your pipeline instead of `NuglifyJs`
