### ISSUE TITLE
Cache busting question

### ISSUE THREAD

**Issue by vincentparrett** [Shazwazza/Smidge#91]
It's not exactly clear to me how the cache busting works. I see the version in the smidge config, but do we really have to change that manually to get cache busting to work?

We previously used squishit on .net 4.6 and it uses a hash of the bundle as a query string parameter to do the cache busting. Is there a way we can do the same thing with smidge? I'm happy to have a go at implementing it but just needs some pointers.

**Comment by Shazwazza** [comment]
Hi, cache busting is handled with an [`ICacheBuster`](https://github.com/Shazwazza/Smidge/blob/master/src/Smidge/Cache/ICacheBuster.cs)

The default implementation is [`ConfigCacheBuster`](https://github.com/Shazwazza/Smidge/blob/master/src/Smidge/Cache/ConfigCacheBuster.cs)  which 

Another one is [`AppDomainLifetimeCacheBuster`](https://github.com/Shazwazza/Smidge/blob/master/src/Smidge/Cache/AppDomainLifetimeCacheBuster.cs) which will set a new cache bust value whenever your app restarts.

The cache busting for the browser is done with a query string which is the value returned from `ICacheBuster.GetValue`. 

Cache busting is not only for the browser however it's also for the server side persistent file cache so that bundling/processing/minifying doesn't keep occurring. Once the pipeline is executed those files are persisted to disk based on a cache bust value which is nice when you have the ConfigCacheProvider enabled since the pipeline for your bundles will not be re-executed even when your app restarts (unless you bump the version in your config). Of course if you are running with `AppDomainLifetimeCacheBuster`, then the pipeline will be re-executed for each bundle anytime your app restarts.

There are various ways to change the cache buster type, you can change it globally like: https://github.com/Shazwazza/Smidge/blob/master/src/Smidge.Web/Startup.cs#L72 or you can change it per bundle/environment like https://github.com/Shazwazza/Smidge/blob/master/src/Smidge.Web/Startup.cs#L145

Also note that if file watching is enabled, this also affects cache busting. If watching is enabled then the actual cache bust value is a combination of the ICacheBuster and the watched hash. 

I'm working on a [branch for the next major version](https://github.com/Shazwazza/Smidge/tree/version-4) where some of this is refactored and yes it should also make sure to do a hash of the bundle along with the ICacheBuster.GetValue call so that if your bundle changes it's automatically cache busted. Perhaps a better solution is that the ICacheButer.GetValue should have a parameter passed to it of the bundle so that it can decide exactly how to calculate this.

For now though, i think you could work around this by adding a file watcher like in https://github.com/Shazwazza/Smidge/blob/master/src/Smidge.Web/Startup.cs#L144
