### ISSUE TITLE
Load balancer + browser/edge cache scenario

### ISSUE THREAD

**Issue by J-ohn** [Shazwazza/Smidge#96]
I am writing to ask how would one handle the following scenario with smidge:

Infrastructure:
More than one web server. css/js files are locally on each server along with application binaries. A load balancer sits in front of the web servers and is configured in round-robin mode (i.e. requests are spread out evenly across all servers, no sticky)

Update procedure (CD):
In order to update the application, each individual server is taken out of the load balancer, new files are copied on to it and then is put back in the load balancer. This is repeated for all servers.

Issues arising from this:
Lets say we just finished with Server 1 and just put it back in the balancer pool. We have not removed Server 2 from the balancer pool but are just about to. At that moment a request comes and is served by Server 1. Server 1 has updated css/js files and serves a url for BundleX with the cache buster based on the state of it's files. The request for that bundle goes to the load balancer and it decides that Server 2 should process it (we havent taken it offline yet). Server 2 does not have the updated css/js files so serves the old content. The user's browser therefore caches the new url with old content so does not see the change. This gets worse if there is an edge site cache or cdn in front of the site. The cdn will cache the new url with the old content so every user will not see the change.

This has happened for us with other bundling/minification libraries in the past so I was just wondering if smidge can handle something like this and how.

Thanks in advance
John

**Comment by Shazwazza** [comment]
Hi, that's an interesting topic and one that would be interesting to solve. Since you aren't using sticky sessions it would be difficult to associate one server creating a bundle URL and another one to serve it when there's no guarantee that the 2 servers are in sync. 

I guess the question is how would you want or expect a bundler to handle this scenario? 

Smidge is very customizable and you can implement your own cache buster service. Perhaps part of the cache busting value is the "version" of your new rollout. Perhaps a server can then detect this portion of the cache busting value and if it doesn't match the expectation it could make sure that the results that are returned (that it knows about) have the correct caching headers to ensure that the clients don't cache this result. Off the top of my head i don't know how smidge can be extended to do that but it might be, i'd need to revisit some code. Else I'm sure it can be made possible to do that.

Do you have another way that you could forsee this working?

**Comment by J-ohn** [comment]
I have been going over this for many years actually but couldn't come up with an elegant solution. The solutions I have come up with are either too complicated/messy or require additional actions. Currently we basically change a value in the database via our admin panel after the deployment is done so all cache busters are using this value. This wastes some bandwidth since everything is refreshed but it beats having broken/old content. 

I would think is that an ideal solution would be servers with old content to be able to serve the new bundle content before they get updated. To do this you could have a common storage for the bundle content. i.e. During startup or when a bundle link is generated the bundle is written to disk. It is then served from disk. That disk location could be using some sort of storage (e.g. Azure Blob Storage or a UNC path or a db table or whatever). So when Server 1 generates the new bundle url the bundle would already have been written to disk. When Server 2 receives the request for that new cache bust it will be able to serve the new content.

**Comment by Shazwazza** [comment]
Yep that is one part of a possible solution. Smidge (eventually) will use the abstracted file system so that would be possible (just haven't had a ton of time to invest lately in the next major version).

I have another idea though which is similar to what I mentioned above which might be 'easy'. Smidge's default cache buster is just a string value in config. Let's say for example that the initial value is "1".  When you deploy a new release you'd change or increment this value so your new release now has "2" as the cache bust value.  In this example, Server "A" is updated with the new release and server "B" still has the old build.

If a request comes into Server "A", renders a <script> tag and the client makes that request which ends up on Server "B", then what would be fairly easy I think is that Server "B" would acknowledge that the cache bust value of "2" is not what it's configured for, so in that case the only thing it can do is return what it has for it's own cache bust value **but** because it knows something isn't quite right it adjust the outgoing headers to make sure that the result is not cached.

The only part of this that is missing in Smidge is just detecting that it doesn't have the correct cache bust value and then modify the headers accordingly.
